/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComecarRouteImport } from './routes/comecar'
import { Route as IscaRouteImport } from './routes/isca'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComecarRoute = ComecarRouteImport.update({
  id: '/comecar',
  path: '/comecar',
  getParentRoute: () => rootRouteImport,
} as any)
const IscaRoute = IscaRouteImport.update({
  id: '/isca',
  path: '/isca',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comecar': typeof ComecarRoute
  '/isca': typeof IscaRoute
  '/privacidade': typeof PrivacidadeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comecar': typeof ComecarRoute
  '/isca': typeof IscaRoute
  '/privacidade': typeof PrivacidadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comecar': typeof ComecarRoute
  '/isca': typeof IscaRoute
  '/privacidade': typeof PrivacidadeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/comecar' | '/isca' | '/privacidade'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comecar' | '/isca' | '/privacidade'
  id: '__root__' | '/' | '/comecar' | '/isca' | '/privacidade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComecarRoute: typeof ComecarRoute
  IscaRoute: typeof IscaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comecar': {
      id: '/comecar'
      path: '/comecar'
      fullPath: '/comecar'
      preLoaderRoute: typeof ComecarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isca': {
      id: '/isca'
      path: '/isca'
      fullPath: '/isca'
      preLoaderRoute: typeof IscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComecarRoute: ComecarRoute,
  IscaRoute: IscaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
